set -g status-style 'bg=#181818,fg=#90E0F3'
set -g window-status-style 'bg=#181818,fg=#646464'
set -g window-status-current-style 'bg=#3D3D3D,fg=#DAFFEF,bold'
set -g pane-border-style 'fg=#3D3D3D'
set -g pane-active-border-style 'fg=#90E0F3'
set -g message-style 'bg=#90E0F3,fg=#181818,bold'
