local M = {}

function M.apply(c)
    vim.cmd("highlight clear")
    vim.g.colors_name = "dynamic_palette"

    local groups = {
        -- UI Elements
        Normal       = { bg = c.c0, fg = c.c5 },
        NormalFloat  = { bg = c.c1, fg = c.c5 },
        FloatBorder  = { fg = c.c3, bg = c.c1 },
        CursorLine   = { bg = c.c2 },
        Visual       = { bg = c.c2 },
        LineNr       = { fg = c.c3 },
        CursorLineNr = { fg = c.c12, bold = true },
        Title        = { fg = c.c12, bold = false },

        -- Standard Language Syntax Highlighting
        Comment      = { fg = c.c3, italic = true },
        Constant     = { fg = c.c15 },
        String       = { fg = c.c7 },
        Character    = { fg = c.c7 },
        Number       = { fg = c.c15 },
        Boolean      = { fg = c.c15, bold = false },
        Float        = { fg = c.c15 },
        Identifier   = { fg = c.c5 },
        Function     = { fg = c.c14 },
        Statement    = { fg = c.c11 },
        Conditional  = { fg = c.c11 },
        Repeat       = { fg = c.c11 },
        Label        = { fg = c.c11 },
        Operator     = { fg = c.c5 },
        Keyword      = { fg = c.c11, bold = false },
        Exception    = { fg = c.c11 },
        PreProc      = { fg = c.c13 },
        Include      = { fg = c.c13 },
        Define       = { fg = c.c13 },
        Macro        = { fg = c.c13 },
        PreCondit    = { fg = c.c13 },
        Type         = { fg = c.c12 },
        StorageClass = { fg = c.c12 },
        Structure    = { fg = c.c12 },
        Typedef      = { fg = c.c12 },
        Special      = { fg = c.c13 },
        Delimiter    = { fg = c.c5 },
        Underlined   = { underline = true },
        Bold         = { bold = true },
        Italic       = { italic = true },
        Error        = { fg = c.c11, reverse = true },
        Todo         = { fg = c.c12, bold = true, italic = true },

        -- Treesitter Capture Query Extensions (Neovim 0.8+)
        ["@comment"]              = { link = "Comment" },
        ["@none"]                 = { bg = "NONE", fg = "NONE" },
        ["@preproc"]              = { link = "PreProc" },
        ["@define"]               = { link = "Define" },
        ["@operator"]             = { link = "Operator" },
        ["@punctuation.delimiter"] = { fg = c.c5 },
        ["@punctuation.bracket"]   = { fg = c.c5 },
        ["@punctuation.special"]   = { fg = c.c13 },
        ["@string"]               = { link = "String" },
        ["@string.regex"]         = { fg = c.c13 },
        ["@string.escape"]        = { fg = c.c13 },
        ["@character"]            = { link = "Character" },
        ["@character.special"]    = { link = "Special" },
        ["@number"]               = { link = "Number" },
        ["@boolean"]              = { link = "Boolean" },
        ["@float"]                = { link = "Float" },
        ["@function"]             = { link = "Function" },
        ["@function.builtin"]     = { fg = c.c14 },
        ["@function.call"]        = { link = "Function" },
        ["@function.macro"]       = { link = "Macro" },
        ["@method"]               = { link = "Function" },
        ["@method.call"]          = { link = "Function" },
        ["@constructor"]          = { fg = c.c12 },
        ["@parameter"]            = { fg = c.c5 },
        ["@keyword"]              = { link = "Keyword" },
        ["@keyword.function"]     = { fg = c.c11, bold = false },
        ["@keyword.operator"]     = { fg = c.c11 },
        ["@keyword.return"]       = { fg = c.c11, bold = false },
        ["@conditional"]          = { link = "Conditional" },
        ["@repeat"]               = { link = "Repeat" },
        ["@debug"]                = { fg = c.c11 },
        ["@label"]                = { link = "Label" },
        ["@include"]              = { link = "Include" },
        ["@exception"]            = { link = "Exception" },
        ["@type"]                 = { link = "Type" },
        ["@type.builtin"]         = { fg = c.c12 },
        ["@type.definition"]      = { link = "Typedef" },
        ["@type.qualifier"]       = { fg = c.c11 },
        ["@storageclass"]         = { link = "StorageClass" },
        ["@attribute"]            = { fg = c.c14 },
        ["@field"]                = { fg = c.c5 },
        ["@property"]             = { fg = c.c5 },
        ["@variable"]             = { fg = c.c6 },
        ["@variable.builtin"]     = { fg = c.c10 },
        ["@variable.parameter"]   = { fg = c.c5 },
        ["@variable.member"]      = { fg = c.c5 },
        ["@constant"]             = { link = "Constant" },
        ["@constant.builtin"]     = { fg = c.c15, bold = false },
        ["@constant.macro"]       = { link = "Macro" },
        ["@tag"]                  = { fg = c.c11 },
        ["@tag.attribute"]        = { fg = c.c14 },
        ["@tag.delimiter"]        = { fg = c.c5 },
        ["@text"]                 = { fg = c.c5 },
        ["@text.strong"]          = { bold = true },
        ["@text.emphasis"]        = { italic = true },
        ["@text.underline"]       = { underline = true },
        ["@text.strike"]          = { strikethrough = true },
        ["@text.title"]           = { link = "Title" },
        ["@text.literal"]         = { fg = c.c7 },
        ["@text.uri"]             = { fg = c.c8, underline = true },
    }

    for group, settings in pairs(groups) do
        vim.api.nvim_set_hl(0, group, settings)
    end
end

return M
